services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: rails_101
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    working_dir: /rails_101  # 明示的に指定が必要
    volumes:
      - .:/rails_101/
    depends_on:
      - db
volumes:
  mysql_data:
